<%@ Page Language="C#"  AutoEventWireup="true" MasterPageFile="~/IFrameMaster.Master" CodeBehind="Default.aspx.cs" Inherits="IFrameSample.Default" %>

<%@ MasterType VirtualPath="~/IFrameMaster.Master" %>

<asp:Content runat="server" ContentPlaceHolderID="head">
    <script type="text/javascript">
        function pickColor(color) {
            saveColor(color); // this function generated by Page_Load method
            var templateData = new Object();
            templateData.color = color;
            FB.Connect.showFeedDialog("101489467051", templateData, null, "", null, FB.RequireConnect.require, feedSent);
        }

        function feedSent() {
            submitForm(); // this function dynamically generated by Page_Load method
        }
    </script>
</asp:Content>

<asp:Content runat="server" ID="content" ContentPlaceHolderID="body">
    <form action="Default.aspx" id="form" runat="server">
        <h2><fb:name firstnameonly="true" useyou="false" linked="false" uid="loggedinuser"></fb:name>, what is your favorite color?</h2>
        <ul>
            <li onclick="pickColor('red')">
                <div style="background-color: Red"></div>
                <p>Red</p>
            </li>
            <li onclick="pickColor('orange')">
                <div style="background-color: Orange"></div>
                <p>Orange</p>
            </li>
            <li onclick="pickColor('yellow')">
                <div style="background-color: Yellow"></div>
                <p>Yellow</p>
            </li>
            <li onclick="pickColor('green')">
                <div style="background-color: Green"></div>
                <p>Green</p>
            </li>
            <li onclick="pickColor('blue')">
                <div style="background-color: Blue"></div>
                <p>Blue</p>
            </li>
            <li onclick="pickColor('purple')">
                <div style="background-color: Purple"></div>
                <p>Purple</p>
            </li>
        </ul>
        
        <asp:Panel ID="emailPermissionPanel" runat="server">
            <p>If you would like this application to send you e-mail messages, please <fb:prompt-permission perms="email">click here</fb:prompt-permission>.</p>
        </asp:Panel>
        
        <asp:HiddenField runat="server" ID="colorInput" />
    </form>
</asp:Content>
